### ISSUE TITLE
how to  install Diamond 

### ISSUE THREAD

**Issue by leejshades** [cloudify-examples/nodecellar-auto-scale-auto-heal-blueprint#24]
error:
Invalid blueprint - Plugin cloudify-diamond-plugin (query: {'package_name': 'cloudify-diamond-plugin'}) not found
I try "pip install diamond"
but ,not work.

**Comment by EarthmanT** [comment]
You need to [install the plugin](https://github.com/cloudify-examples/nodecellar-auto-scale-auto-heal-blueprint#pre-installation-steps).

```
cfy plugins upload [wagon_url_or_path] -y [plugin_yaml_url_or_path]
```

for example:

```
cfy plugins upload http://repository.cloudifysource.org/cloudify/wagons/cloudify-diamond-plugin/1.3.8/cloudify_diamond_plugin-1.3.8-py27-none-linux_x86_64-centos-Core.wgn -y http://www.getcloudify.org/spec/diamond-plugin/1.3.8/plugin.yaml
```

**Comment by leejshades** [comment]
Awesome，
