### ISSUE TITLE
hi,can u help me ?

### ISSUE THREAD

**Issue by leejshades** [cloudify-examples/nodecellar-auto-scale-auto-heal-blueprint#25]
error:
 RuntimeError(message)
RuntimeError: Workflow failed: Task failed  -> Failed configuring agent installer: The network associated  the agent (`external`) does  appear  the list of manager networks assigned at bootstrap (default)
my openstack network:

![qq 20180620100942](https://user-images.githubusercontent.com/7189444/41633562-1e406962-7472-11e8-9d60-0d16da560b8b.png)

**Comment by leejshades** [comment]
I try to use network id ,it does not work.
![qq 20180620103234](https://user-images.githubusercontent.com/7189444/41634246-6b3639ec-7475-11e8-9dce-2c2d7165fbae.png)
![qq 20180620103251](https://user-images.githubusercontent.com/7189444/41634249-6e1cf312-7475-11e8-9066-b028fb92247a.png)

**Comment by EarthmanT** [comment]
Hello, Please install this blueprint first: https://github.com/cloudify-examples/openstack-example-network/blob/master/simple-blueprint.yaml.
