### ISSUE TITLE
hi,can you give me some advice

### ISSUE THREAD

**Issue by leejshades** [cloudify-examples/nodecellar-auto-scale-auto-heal-blueprint#26]
![qq 20180620163305](https://user-images.githubusercontent.com/7189444/41646966-a9891b7e-74a7-11e8-9dba-a1b8ac51b526.png)
my openstack networks
![qq 20180620163517](https://user-images.githubusercontent.com/7189444/41647081-f7626fbc-74a7-11e8-8204-2a096d8fea0c.png)

**Comment by screwgoth** [comment]
@hadesleejs In order for you to run this Cloudify example on Openstack, you need to first depoy a Cloudify Openstack environment as per this : https://github.com/cloudify-examples/cloudify-environment-setup
Once this is up and running, try running this script again.

**Comment by EarthmanT** [comment]
Hello, Please install this blueprint first: https://github.com/cloudify-examples/openstack-example-network/blob/master/simple-blueprint.yaml.

**Comment by EarthmanT** [comment]
Hi please see the docs section on multi management networks
https://docs.cloudify.co/4.3.0/install_maintain/installation/installing-manager/

**Comment by leejshades** [comment]
@screwgoth thank you for your help，but when i finish "openstack-example-network "
cloudify dashboard:
![qq 20180709162430](https://user-images.githubusercontent.com/7189444/42439139-956768b6-8394-11e8-8690-8bd00568991f.png)
openstack dashboard:
![qq 20180709162553](https://user-images.githubusercontent.com/7189444/42439203-c4a4d26c-8394-11e8-810f-f53d898c014f.png)
But now,There's the same problem.
![qq 20180709162710](https://user-images.githubusercontent.com/7189444/42439258-f330174a-8394-11e8-94c5-f3e8b59724f3.png)
We look forward to your reply.
thank you.

**Comment by leejshades** [comment]
@EarthmanT  i use image qcow2 for openstack ,
![qq 20180709165112](https://user-images.githubusercontent.com/7189444/42440486-7cb915e0-8398-11e8-9800-74ee00554ca1.png)

**Comment by leejshades** [comment]
how to explain "manager_network"/??

**Comment by EarthmanT** [comment]
you need to use a clean Centos or RH machine and install the RPM, configure networks and then install Cloudify if you want to use the examples.

**Comment by leejshades** [comment]
got it ,thanks
