### ISSUE TITLE
Nodecellar application needs aws-example-network deployment

### ISSUE THREAD

**Issue by screwgoth** [cloudify-examples/nodecellar-auto-scale-auto-heal-blueprint#27]
Currently, in order to deploy this Nodecellar example on AWS, you need to have the aws-example-network deployment installed.
Which means, even if you have a AWS setup using : https://github.com/cloudify-examples/cloudify-environment-setup , you still need to install the `aws-example-network` blueprint.
I should be able to deploy this application without a tight dependency on `aws-example-network` deployment

**Comment by screwgoth** [comment]
This issue is fixed by PR #28

**Comment by EarthmanT** [comment]
Hi,
All of the Cloudify examples are intended to be used on a single example network.
